//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SequenceClient.SequenceService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SequenceService.ISequenceService")]
    public interface ISequenceService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISequenceService/Translate", ReplyAction="http://tempuri.org/ISequenceService/TranslateResponse")]
        string Translate(string seq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISequenceService/Translate", ReplyAction="http://tempuri.org/ISequenceService/TranslateResponse")]
        System.Threading.Tasks.Task<string> TranslateAsync(string seq);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISequenceServiceChannel : SequenceClient.SequenceService.ISequenceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SequenceServiceClient : System.ServiceModel.ClientBase<SequenceClient.SequenceService.ISequenceService>, SequenceClient.SequenceService.ISequenceService {
        
        public SequenceServiceClient() {
        }
        
        public SequenceServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SequenceServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SequenceServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SequenceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Translate(string seq) {
            return base.Channel.Translate(seq);
        }
        
        public System.Threading.Tasks.Task<string> TranslateAsync(string seq) {
            return base.Channel.TranslateAsync(seq);
        }
    }
}
